[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.83"

[dev-dependencies]
cargo-watch = "8.3.0"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
